; generated by Component: ARM Compiler 5.06 update 7 (build 960) Tool: ArmCC [4d365d]
; commandline ArmCC [--c99 --split_sections --debug -c -S -ort_thread\main.s --depend=rt_thread\main.d --cpu=Cortex-M4.fp.sp --apcs=interwork -O3 --diag_suppress=9931 -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I..\Src -I..\Include -I..\Libcpu -I..\Source -I..\Test -I.\RTE\_rt_thread -IC:\Users\LT\AppData\Local\Arm\Packs\ARM\CMSIS\5.8.0\CMSIS\Core\Include -IC:\Users\LT\AppData\Local\Arm\Packs\Keil\STM32F4xx_DFP\2.15.0\Drivers\CMSIS\Device\ST\STM32F4xx\Include -D__UVISION_VERSION=536 -D_RTE_ -DSTM32F407xx -D_RTE_ -DUSE_HAL_DRIVER -DSTM32F407xx --omf_browse=rt_thread\main.crf ../Core/Src/main.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||i.Error_Handler||, CODE, READONLY, ALIGN=1

Error_Handler PROC
        CPSID    i
|L0.2|
        B        |L0.2|
        ENDP


        AREA ||i.SystemClock_Config||, CODE, READONLY, ALIGN=2

SystemClock_Config PROC
        PUSH     {r4,r5,lr}
        SUB      sp,sp,#0x4c
        MOVS     r1,#0x30
        MOV      r0,sp
        BL       __aeabi_memclr4
        MOVS     r1,#0x14
        ADD      r0,sp,#0x30
        BL       __aeabi_memclr4
        LDR      r0,|L1.140|
        MOVS     r5,#0
        LDR      r1,[r0,#0]
        ORR      r1,r1,#0x10000000
        STR      r1,[r0,#0]
        LDR      r0,[r0,#0]
        AND      r0,r0,#0x10000000
        STR      r0,[sp,#0x44]
        LDR      r0,|L1.144|
        LDR      r1,[r0,#0]
        ORR      r1,r1,#0x4000
        STR      r1,[r0,#0]
        LDR      r0,[r0,#0]
        MOVS     r4,#2
        AND      r0,r0,#0x4000
        STR      r0,[sp,#0x44]
        MOVS     r0,#1
        STR      r0,[sp,#0xc]
        MOVS     r0,#0x10
        STR      r0,[sp,#0x10]
        STR      r4,[sp,#0]
        STR      r4,[sp,#0x18]
        MOVS     r0,#8
        STRD     r5,r0,[sp,#0x1c]
        MOVS     r0,#0xa8
        STRD     r0,r4,[sp,#0x24]
        MOVS     r0,#4
        STR      r0,[sp,#0x2c]
        MOV      r0,sp
        BL       HAL_RCC_OscConfig
        CBZ      r0,|L1.100|
        CPSID    i
|L1.98|
        B        |L1.98|
|L1.100|
        ADD      r1,sp,#0x30
        MOVS     r0,#0xf
        STM      r1,{r0,r4,r5}
        MOV      r0,#0x1400
        STR      r0,[sp,#0x3c]
        MOV      r0,#0x1000
        STR      r0,[sp,#0x40]
        MOVS     r1,#5
        ADD      r0,sp,#0x30
        BL       HAL_RCC_ClockConfig
        CMP      r0,#0
        BEQ      |L1.136|
        CPSID    i
|L1.134|
        B        |L1.134|
|L1.136|
        ADD      sp,sp,#0x4c
        POP      {r4,r5,pc}
        ENDP

|L1.140|
        DCD      0x40023840
|L1.144|
        DCD      0x40007000

        AREA ||i.main||, CODE, READONLY, ALIGN=2

main PROC
        BL       HAL_Init
        BL       SystemClock_Config
        BL       MX_GPIO_Init
        LDR      r0,|L2.28|
        MOVS     r1,#3
        VMOV.F32 s0,#2.00000000
|L2.20|
        STR      r1,[r0,#4]  ; check
        VSTR     s0,[r0,#0]
        B        |L2.20|
        ENDP

|L2.28|
        DCD      ||.data||

        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

        AREA ||.data||, DATA, ALIGN=2

Light
        DCFS     0x40400000 ; 3
check
        DCD      0x00000001

;*** Start embedded assembler ***

#line 1 "../Core/Src/main.c"
	AREA ||.rev16_text||, CODE
	THUMB
	EXPORT |__asm___6_main_c_Light____REV16|
#line 463 "../Drivers/CMSIS/Include/cmsis_armcc.h"
|__asm___6_main_c_Light____REV16| PROC
#line 464

 rev16 r0, r0
 bx lr
	ENDP
	AREA ||.revsh_text||, CODE
	THUMB
	EXPORT |__asm___6_main_c_Light____REVSH|
#line 478
|__asm___6_main_c_Light____REVSH| PROC
#line 479

 revsh r0, r0
 bx lr
	ENDP
	AREA ||.rrx_text||, CODE
	THUMB
	EXPORT |__asm___6_main_c_Light____RRX|
#line 665
|__asm___6_main_c_Light____RRX| PROC
#line 666

 rrx r0, r0
 bx lr
	ENDP

;*** End   embedded assembler ***

__ARM_use_no_argv EQU 0

        EXPORT __ARM_use_no_argv
        EXPORT Error_Handler [CODE]
        EXPORT SystemClock_Config [CODE]
        EXPORT main [CODE]
        EXPORT Light [DATA,SIZE=4]
        EXPORT check [DATA,SIZE=4]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]
        IMPORT __aeabi_memclr4 [CODE]
        IMPORT HAL_RCC_OscConfig [CODE]
        IMPORT HAL_RCC_ClockConfig [CODE]
        IMPORT HAL_Init [CODE]
        IMPORT MX_GPIO_Init [CODE]

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,3
        ATTR SETSTRING Tag_conformance,"2.09"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
